# Generated by Django 5.2.5 on 2025-08-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationwide_patient_secure_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='full_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='surname',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
