# Generated by Django 5.2.5 on 2025-08-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationwide_patient_secure_api', '0002_remove_patient_full_name_patient_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='adress',
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
