# Generated by Django 5.2.5 on 2025-09-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationwide_patient_secure_api', '0003_remove_hospital_adress_hospital_hospital_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_picture',
            field=models.ImageField(blank=True, null=True, upload_to='patient/photos/'),
        ),
    ]
