# Generated by Django 5.2.5 on 2025-09-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationwide_patient_secure_api', '0004_patient_patient_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_picture',
            field=models.ImageField(blank=True, null=True, upload_to='patient/'),
        ),
    ]
