# Generated by Django 5.2.5 on 2025-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationwide_patient_secure_api', '0005_alter_patient_patient_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
