# Generated by Django 5.2.5 on 2025-09-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nationwide_patient_secure_api', '0006_patient_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='slug',
        ),
    ]
