# Generated by Django 5.2.5 on 2025-09-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nationwide_patient_secure_api', '0007_remove_patient_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_picture',
        ),
    ]
