# Generated by Django 5.2.5 on 2025-09-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationwide_patient_secure_api', '0008_remove_patient_patient_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='patient/'),
        ),
    ]
